title: Xiaolong Hou's Homepage
page-top-title: Xiaolong (Chris) Hou
top-section-bg-text: 
home-subtitle: Xiaolong Hou&ensp;|&ensp;侯小龙
copyright-text: '&copy; Xiaolong Hou 2023-2024. All Rights Reserved.'
